### ISSUE TITLE
[Gameplay] Investigate discrepancy with simulated tests when shown on Thunderscope and Replay logs

### ISSUE THREAD

**Issue by itsarune** [UBC-Thunderbots/Software#2850] opened 2023-03-03 04:58 UTC
### Description of the task

Often in pytests, simulated tests pass with Thunderscope and not in headless mode and vice versa. Investigate and fix this bug.

Tests that I've seen with this issue is:
`ball_placement_play_test.py`
`pass_defender_tactic_test.py`

### Acceptance criteria

- [ ] Identify the problem with discrepancies between simulated gameplay tests with/without GUI

**Comment by williamckha** [comment] 2023-04-01 18:43
Duplicate of #2858

**Comment by nimazareian** [comment] 2023-10-30 21:03
#3029 should have fixed this. Re-open if this continues to happen

**Closed as completed by nimazareian** 2023-10-30 21:03 UTC
Labels: Difficulty - 7
